### ISSUE TITLE
calico network policy

### ISSUE THREAD

**Issue by kristina-reut** [AliyunContainerService/terway#107]
Hi! Could you please verify if it's possible to use Calico Network Policy with Terway? Or is it possible to integrate calico network with terway ?
For example,
```
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: allow-tcp-6379
spec:
  selector: role == 'database'
  types:
  - Ingress
  - Egress
  ingress:
  - action: Allow
    metadata:
      annotations:
        from: frontend
        to: database
    protocol: TCP
    source:
      selector: role == 'frontend'
    destination:
      ports:
      - 6379
  egress:
  - action: Allow
```
