### ISSUE TITLE
unknown field "aliyun/eni" in io.k8s.api.core.v1.ResourceRequirements

### ISSUE THREAD

**Issue by zrbcool** [AliyunContainerService/terway#13]
met error when i change my deployment to use terway ENI mode
```
# Pleasese edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
# deployments.extensions "iperf3-terway" was not valid:
# * : Invalid value: "The edited file failed validation": ValidationError(Deployment.spec.template.spec.containers[0].resources): unknown field "aliyun/eni" in io.k8s.api.core.v1.ResourceRequirements
```

**Comment by BSWANG** [comment]
Hi，Which version kubernetes you using? 
This `resource requirement` depends on kubernetes `device plugin` feature. This feature support after 1.10 kubernetes version.

**Comment by zrbcool** [comment]
we are using version 1.12.6-aliyun.1, and following is our deployment.yaml
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    run: iperf3-terway
  name: iperf3-terway
spec:
  replicas: 3
  selector:
    matchLabels:
      run: iperf3-terway
...
  template:
    metadata:
      labels:
        run: iperf3-terway
    spec:
      containers:
      - args:
        - -s
        - -i
        - "1"
        - -p
        - "16000"
        resources:
          limits:
            aliyun/eni: 1
        image: networkstatic/iperf3
        imagePullPolicy: Always
        name: iperf3-terway
        resources: {}
      restartPolicy: Always
...
```
